name: alarm_front
description: JUNOMonitor is a Jiangmen neutrino monitoring software.
publish_to: 'none'
version: 1.1.5+10105

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  universal_platform: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7
  dartx: ^1.2.0
  fl_chart: ^0.70.2  
  flutter_bloc: ^8.1.6
  package_info_plus: ^8.0.2
  equatable: ^2.0.5
  intl: ^0.20.1
  web_socket_channel: ^3.0.2
  permission_handler: ^11.2.0
  flutter_local_notifications: ^19.3.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  path_provider: ^2.1.2
  vibration: ^3.1.3
  shared_preferences: ^2.3.2
  
  # 添加文件上传相关依赖【推拽上传、点击上传】
  file_picker: ^10.2.0
  http: ^1.2.1
  path: ^1.9.0
  dotted_border: ^2.1.0
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/data/
    - lib/config/

# 应用图标配置 (已生成，保留此配置以便将来更新图标)
# 使用方法: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/app_logo_1024.png"
